import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export function exportAnalysisPDF(result) {
  const doc = new jsPDF();

  // ===========================
  // TITLE
  // ===========================

  doc.setFontSize(18);
  doc.setTextColor(40, 40, 40);

  doc.text(
    "Creation of Intelligent Bug Diagnosis Platform",
    20,
    20
  );

  doc.setFontSize(14);
  doc.setTextColor(0, 102, 204);

  doc.text(
    "AI-Powered Fix Recommendation Assistance",
    20,
    30
  );

  doc.setFontSize(12);
  doc.setTextColor(80);

  doc.text(
    `Generated: ${new Date().toLocaleString()}`,
    20,
    40
  );

  // ===========================
  // TRIAGE DETAILS
  // ===========================

  autoTable(doc, {
    startY: 50,

    head: [["Field", "Value"]],

    body: [
      [
        "Severity",
        result.analysis?.triage?.severity || "-"
      ],

      [
        "Priority",
        result.analysis?.triage?.priority || "-"
      ],

      [
        "Component",
        result.analysis?.triage?.component || "-"
      ],

      [
        "Confidence",
        result.analysis?.triage?.confidence || "-"
      ],

      [
        "Exception",
        result.analysis?.log_analysis?.exception_type || "-"
      ],

      [
        "Failure Point",
        result.analysis?.log_analysis?.failure_point || "-"
      ],
    ],

    theme: "striped",

    headStyles: {
      fillColor: [30, 64, 175],
    },
  });

  let y = doc.lastAutoTable.finalY + 12;

  // ===========================
  // ROOT CAUSE
  // ===========================

  doc.setFontSize(15);
  doc.setTextColor(30);

  doc.text("Root Cause", 20, y);

  y += 8;

  doc.setFontSize(11);
  doc.setTextColor(70);

  const rootCause =
    result.analysis?.root_cause?.root_cause ||
    result.analysis?.root_cause ||
    "No root cause available.";

  doc.text(
    doc.splitTextToSize(rootCause, 170),
    20,
    y
  );

  y += 28;

  // ===========================
  // AI RECOMMENDATION
  // ===========================

  doc.setFontSize(15);
  doc.setTextColor(30);

  doc.text("AI Recommendation", 20, y);

  y += 8;

  doc.setFontSize(11);
  doc.setTextColor(70);

  const recommendation =
    result.analysis?.fix_recommendation?.recommended_fix ||
    result.analysis?.fix_recommendation?.recommendation ||
    "No recommendation available.";

  doc.text(
    doc.splitTextToSize(recommendation, 170),
    20,
    y
  );

  // ===========================
  // FOOTER
  // ===========================

  doc.setFontSize(9);
  doc.setTextColor(130);

  doc.text(
    "Generated by Creation of Intelligent Bug Diagnosis Platform with AI-Powered Fix Recommendation Assistance",
    20,
    285
  );

  // ===========================
  // SAVE PDF
  // ===========================

  doc.save("Intelligent_Bug_Diagnosis_Report.pdf");
}